version: '3.7'

services:
  stats_node_db:
    image: mongo:latest
    container_name: stats_node_db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - stats_node_db:/data/db
      - ./dump:/dump
    ports:
      - 27017:27017

volumes:
  stats_node_db:
